promise.then(f1).catch(f2);
// vs
promise.then(f1, f2);

// Будут вести себя по разному
// В 1 случае если ошибка произойдёт она будет сразу отловлена
// без выполнения then и если даже ошибка произоёдет в then, 
// то она всё ровно будет отловлена

// Во втором случае ошибка также обработается, но если промис
// отработает нормально, запустится f1 и будет ошибка,
// то она уже никак не отработается